---
-
  name: This playbook is for my webserver
  hosts: localhost
  connection: local

  tasks:
    -
      name: Installing webserver package
      yum:
        name: httpd
        state: present

    -
      name: Configuring webserver file
      copy:
        dest: /var/www/html/index.html
        content: "<h1>This page has been created using the Power of Ansible Automation</h1>"

    -
      name: Start webserver application
      service:
        name: httpd
        state: started
        enabled: yes

    -
      name: Remove the packages for pre-req
      yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent

    -
      name: Installing pre-req package for Docker
      yum:
        name: yum-utils
        state: present

    -
      name: Adding docker official repo
      get_url:
        dest: /etc/yum.repos.d/docker-ce.repo
        url: https://download.docker.com/linux/centos/docker-ce.repo

    -
      name: Installing Docker Software
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    -
      name: Starting and enabling Docker Services
      service:
        name: docker
        state: started
        enabled: yes

    -
      name: downloading image
      command: "docker image pull httpd"

    -
      name: create a docker conatiner
      command: "docker container run -itd --name=mycontainer httpd:latest"

